### PR TITLE
Nancy berry

### PR DESCRIPTION
**Pull request by Nancyberry31**
I need your help God

### CODE REVIEW

**Comment by Nancyberry31** [comment]
My God please help me please I need your help please God 
IMG_16976752725106193

**Comment by Nancyberry31** [comment]
Please God I need your blessing please God

**Comment by Nancyberry31** [comment]
God bless me please

**Comment by Nancyberry31** [comment]
I need your blessing please God

**Comment by kingjollie** [comment]
Why do you need god?

**Comment by ly-nld** [comment]
I’m confused, are you in danger?

**Pull request closed without merging**
